apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url
spec:
  selector:
    matchLabels:
      app: short-url
  template:
    metadata:
      labels:
        app: short-url
    spec:
      containers:
        - name: short-url-backend
          image: anshuld12/short-url:base
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: short-url-configmap
