apiVersion: v1
kind: Service
metadata:
  name: creators-connect-service
spec:
  selector:
    app: creators-connect
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000
