apiVersion: v1
kind: Service
metadata:
  name: short-url-service
spec:
  selector:
    app: short-url
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000
